---

- name: "daily email reminders"
  cron:
    user: "{{ main_user }}"
    name: "daily email reminders"
    hour: "9"
    minute: "0"
    job: "/usr/local/bin/{{ project_slug }}-ctl send_email_reminders"
