---

organization_slug: telescoop
project_slug: my-project
main_user: my-project
public_hostnames:
  - app.{{ project_slug }}.com
  - "{{ project_slug }}.{{ organization_slug }}.fr"
django_project_name: my_project_back
backend_repo: git@gitlab.com:{{ organization_slug }}/{{ project_slug }}/{{ my_project_back }}.git
frontend_repo:
  git@gitlab.com:{{ organization_slug }}/{{ project_slug }}/{{ project_slug }}_front.git
backend_application_port: 8064
backend_static_path: /{{ organization_slug }}/{{ project_slug}}/backend_static
identity_file_path: /home/ubuntu/.ssh/id_rsa
var_log_path: /var/log/{{ organization_slug }}/{{ project_slug }}
